-- Disable FOREIGN KEY check
-- An unsafe way to prevent errors when dropping tables that have existing data. 

SET FOREIGN_KEY_CHECKS = 0;

-- Create Tables

DROP TABLE IF EXISTS `PRODUCT`;
CREATE TABLE `PRODUCT` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `sku` VARCHAR(255) NOT NULL UNIQUE,
    `price` DECIMAL(10, 2) UNSIGNED NOT NULL ,
    `quantity` INT UNSIGNED NOT NULL ,
    `threshold` INT NOT NULL DEFAULT -1,
    `name` LONGTEXT NOT NULL,
    `description` LONGTEXT,
    `thumbnail_image` LONGTEXT,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `PRODUCT_IMAGE`;
CREATE TABLE `PRODUCT_IMAGE` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `product_id` INT,
    `name` LONGTEXT NOT NULL,
    `extension` VARCHAR(255) NOT NULL, 
    `order` INT NOT NULL DEFAULT -1,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `PRODUCT_CATEGORY`;
CREATE TABLE `PRODUCT_CATEGORY` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `product_id` INT NOT NULL,
    `category_id` INT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `CATEGORY`;
CREATE TABLE `CATEGORY` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` LONGTEXT NOT NULL,
    `description` LONGTEXT,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `COUPON`;
CREATE TABLE `COUPON` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `code` VARCHAR(255) NOT NULL UNIQUE,
    `value` DECIMAL(10, 2) UNSIGNED NOT NULL,
    `type` INT NOT NULL DEFAULT 0,
    `description` LONGTEXT,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `first_name` VARCHAR(255) NOT NULL,
    `middle_name` VARCHAR(255),
    `last_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` LONGTEXT NOT NULL,
    `role` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `first_name` VARCHAR(255) NOT NULL,
    `middle_name` VARCHAR(255),
    `last_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` LONGTEXT NOT NULL,
    `shipping_address_1` VARCHAR(255),
    `shipping_address_2` VARCHAR(255),
    `shipping_address_city` VARCHAR(255),
    `shipping_address_state` VARCHAR(255),
    `shipping_address_zip` VARCHAR(255),
    `billing_address_1` VARCHAR(255),
    `billing_address_2` VARCHAR(255),
    `billing_address_city` VARCHAR(255),
    `billing_address_state` VARCHAR(255),
    `billing_address_zip` VARCHAR(255),
    `card_name` VARCHAR(255),
    `card_number` VARCHAR(255),
    `card_expire_month` VARCHAR(255),
    `card_expire_year` VARCHAR(255),
    `card_code` VARCHAR(255),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `SUBSCRIPTION`;
CREATE TABLE `SUBSCRIPTION` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `customer_id` INT NOT NULL,
    `price` DECIMAL(10, 2) UNSIGNED NOT NULL,
    `start_at` TIMESTAMP NOT NULL,
    `end_at` TIMESTAMP NOT NULL,
    `billing_address_1` VARCHAR(255),
    `billing_address_2` VARCHAR(255),
    `billing_address_city` VARCHAR(255),
    `billing_address_state` VARCHAR(255),
    `billing_address_zip` VARCHAR(255),
    `card_name` VARCHAR(255),
    `card_number` VARCHAR(255),
    `card_expire_month` VARCHAR(255),
    `card_expire_year` VARCHAR(255),
    `card_code` VARCHAR(255),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE `ORDER` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `customer_id` INT,
    `email` VARCHAR(255) NOT NULL,
    `is_subscription` BOOLEAN NOT NULL DEFAULT false,
    `tracking_info` LONGTEXT,
    `status` INT NOT NULL DEFAULT 0,
    `shipping_address_1` VARCHAR(255),
    `shipping_address_2` VARCHAR(255),
    `shipping_address_city` VARCHAR(255),
    `shipping_address_state` VARCHAR(255),
    `shipping_address_zip` VARCHAR(255),
    `billing_address_1` VARCHAR(255),
    `billing_address_2` VARCHAR(255),
    `billing_address_city` VARCHAR(255),
    `billing_address_state` VARCHAR(255),
    `billing_address_zip` VARCHAR(255),
    `card_name` VARCHAR(255),
    `card_number` VARCHAR(255),
    `card_expire_month` VARCHAR(255),
    `card_expire_year` VARCHAR(255),
    `card_code` VARCHAR(255),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `ORDER_COUPON`;
CREATE TABLE `ORDER_COUPON` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `order_id` INT NOT NULL,
    `coupon_id` INT NOT NULL,
    `value` DECIMAL(10, 2) UNSIGNED NOT NULL,
    `type` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `ORDER_PRODUCT`;
CREATE TABLE `ORDER_PRODUCT` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `order_id` INT NOT NULL,
    `product_id` INT NOT NULL,
    `price` DECIMAL(10, 2) UNSIGNED NOT NULL,
    `quantity` INT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `NOTIFICATION`;
CREATE TABLE `NOTIFICATION` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `employee_id` INT NOT NULL,
    `title` LONGTEXT NOT NULL,
    `description` LONGTEXT,
    `type` INT NOT NULL DEFAULT 0,
    `status` INT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

DROP TABLE IF EXISTS `CONFIG`;
CREATE TABLE `CONFIG` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `key` LONGTEXT NOT NULL,
    `value` LONGTEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `is_deleted` BOOLEAN NOT NULL DEFAULT false
);

-- Create FOREIGN KEY constraints  

ALTER TABLE `PRODUCT_IMAGE` ADD FOREIGN KEY (`product_id`) REFERENCES `PRODUCT`(`id`);

ALTER TABLE `PRODUCT_CATEGORY` ADD FOREIGN KEY (`product_id`) REFERENCES `PRODUCT`(`id`);
ALTER TABLE `PRODUCT_CATEGORY` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORY`(`id`);

ALTER TABLE `SUBSCRIPTION` ADD FOREIGN KEY (`customer_id`) REFERENCES `CUSTOMER`(`id`);

ALTER TABLE `ORDER` ADD FOREIGN KEY (`customer_id`) REFERENCES `ORDER`(`id`);

ALTER TABLE `ORDER_COUPON` ADD FOREIGN KEY (`order_id`) REFERENCES `ORDER`(`id`);
ALTER TABLE `ORDER_COUPON` ADD FOREIGN KEY (`coupon_id`) REFERENCES `COUPON`(`id`);

ALTER TABLE `ORDER_PRODUCT` ADD FOREIGN KEY (`order_id`) REFERENCES `ORDER`(`id`);
ALTER TABLE `ORDER_PRODUCT` ADD FOREIGN KEY (`product_id`) REFERENCES `PRODUCT`(`id`);

ALTER TABLE `NOTIFICATION` ADD FOREIGN KEY (`employee_id`) REFERENCES `EMPLOYEE`(`id`);

-- Enable FOREIGN KEY check

SET FOREIGN_KEY_CHECKS = 1;








